[package]
name = "linfa"
version = "0.1.1"
authors = ["Luca Palmieri <rust@lpalmieri.com>"]
description = "A Machine Learning framework for Rust"
edition = "2018"
license = "MIT/Apache-2.0"

repository = "https://github.com/LukeMathWalker/linfa"
readme = "README.md"

keywords = ["machine-learning", "linfa", "ai", "ml"]
categories = ["algorithms", "mathematics", "science"]

[dependencies]
linfa-clustering = "0.1"
linfa-neighbors = {version = "0.1", path = "linfa-neighbors" }

[dev-dependencies]
ndarray = { version = "0.13" , features = ["rayon", "serde", "approx"]}
ndarray-rand = "0.11"
rand_isaac = "0.2.0"
ndarray-npy = { version = "0.5", default-features = false }

[workspace]
members = ["linfa-clustering", "linfa-neighbors"]

[profile.release]
opt-level = 3
